version: '3'
volumes:
  db_data:
    driver: 'local'
services:
  app:
    build: .
    command: ["go", "run", "main.go"]
    volumes:
      - .:/go/src/app
    ports:
      - "8085:8085"
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: s3cr3tp4ssw0rd
    ports:
      - 5432:5432      
    volumes:
      - db_data:/pgdata